sudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y python-pip python-dev
  - sudo apt-get install -q -y python-flake8
  - sudo apt-get install -q -y gdb python2.7-dbg python3.4-dbg

install:
  - pip install -r requirements.txt
  - cython --version
  - gcc --version
  - gdb --version
  - ldd `which gdb`
  - make install

before_script:
  - "flake8 --max-line-length=120 --max-complexity=16 --ignore=E22,E241,E731 src"

script:
  - env  # Display environment variables
  - which python && python --version && ldd `which python`
  - make check-install distcheck check-gdb

notifications:
  on_success: change
  on_failure: always

deploy:
  provider: releases
  api_key:
    secure: nbhpI3eKptUd6TM7nhl8q7oMRztnBEvQmX9/Xks7bmHa+KRy/ifg1/Jx5a7OMnWgzjJ4lbtEO0NDsg/QTOjBsQSV8mot1/NUgXsuPEVpurqTl1KYk9GgX+7utO/KA5mlbXnGkTpzu0/FYHg7qRigWXe7vDILkhst1MR4RTrfA6KzZSq9UKKyNg7eGwWR4tit5OB0z1Ehe1OvdhOlUMBfDBSC5hbM99bm0/oLYNqUeqqP1cRamvpiLaNMVcRG5PRzR/a0QMEGDhZH5BasjFzZZKPa56+J8N/KdRocxrjzIJEYQORgRDyqRrTPEs4jfwL37kcElPNup4j2iefVZ+61bQWk3r3s98MRxl9vk2uLpI0AgfzUn+fpiKuxJNJ424DffJ1iVJSQsKTihww3whOFuf5ZIQS2KtzcZCUHTkD1rX1aawedQ8IaUMx6XWxE+b0x33BroQ04TooDNmww8Q9md6ZauA+4chUlv8YmXaE4NkRRsCxbrcHna5LEz5vFRcvuG/e6PWM9MFUxTzlqHoxgkawJm+DkGe3qWk5a1zut/tesqvrdM1R23G85T6c+FR2wshS5cKcY6OYpYsD5wRJzd0MRKScTCDhEyODydaFRGKQbf2QizFHqN92QYs+rNK4WjVTmHDsETdKczyRJYfsqsTXnw162UjYtwDT5JPJCOlg=

  file: dist/cysignals-*.tar.bz2
  file_glob: true
  skip_cleanup: true
  on:
    repo: sagemath/cysignals
    all_branches: true
    tags: true
